apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd
  namespace: openshift-gitops
spec:
  destination:
    namespace: bgd
    server: https://kubernetes.default.svc
  source:
    path: bgd/base
    repoURL: https://github.com/cipherdmg/gitopts-getting-started
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m