---
# Source: ibm-odm-prod/templates/ds-runtime-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: odm-sno-uat-odm-decisionserverruntime
  labels:
    app: odm-sno-uat-ibm-odm-prod
    chart: "ibm-odm-prod-25.1.10"
    release: "odm-sno-uat"
    heritage: "Helm"
    app.kubernetes.io/instance: odm-sno-uat
    app.kubernetes.io/name: ibm-odm-prod
    app.kubernetes.io/version: "9.5.0.1-IF010"
    app.kubernetes.io/component: decisionServerRuntime
    app.kubernetes.io/part-of: odm
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: ibm-odm-prod-25.1.10
spec:
  selector:
    app: odm-sno-uat-ibm-odm-prod
    release: odm-sno-uat
    run: odm-sno-uat-odm-decisionserverruntime
  type: ClusterIP    
  ports:
   - protocol: TCP
     port: 9443
     name: decisionserverruntime-https
     targetPort: 9443
