apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This works now because it's pointing to a subfolder, not itself
resources:
  - ./ibm-odm-prod

patches:
  - target:
      kind: Secret
      name: odm-sno-uat-ds-auth-sso
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-1"
