{{- if .Values.decisionCenter.autoscaling }}
{{- if .Values.decisionCenter.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "odm.decisioncenter.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionCenter" "root" .) | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "odm.decisioncenter.fullname" . }}
  minReplicas: {{ .Values.decisionCenter.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.decisionCenter.autoscaling.maxReplicas }}
  metrics:
    {{- if and (empty (.Values.decisionCenter.autoscaling.targetAverageUtilization)) (empty (.Values.decisionCenter.autoscaling.targetAverageCpuUtilization)) (empty (.Values.decisionCenter.autoscaling.targetAverageMemoryUtilization)) }}
    {{- required "\nAt least one metric (CPU or Memory) should be used in decisionCenter.autoscaling\n" "" }}
    {{- end }}
    {{- if .Values.decisionCenter.autoscaling.targetAverageUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.decisionCenter.autoscaling.targetAverageUtilization }}
    {{- else }}
    {{- if .Values.decisionCenter.autoscaling.targetAverageCpuUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.decisionCenter.autoscaling.targetAverageCpuUtilization }}
    {{- end }}
    {{- end }}
    {{- if .Values.decisionCenter.autoscaling.targetAverageMemoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.decisionCenter.autoscaling.targetAverageMemoryUtilization }}
    {{- end }}
  {{- if .Values.decisionCenter.autoscaling.behavior }}
  behavior:
{{ toYaml .Values.decisionCenter.autoscaling.behavior | indent 4 }}
  {{- else }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 3000
    scaleUp:
      stabilizationWindowSeconds: 120
  {{- end }}
{{- end }}
{{- end }}
