{{- if and (or .Values.decisionServerRuntime.enabled  .Values.decisionRunner.enabled) .Values.service.enableRoute }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{  template "odm-ds-console-route.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionServerConsole" "root" .) | indent 4 }}
spec:
  {{- if not (empty .Values.decisionServerConsole.routeName ) }}
  host: {{ .Values.decisionServerConsole.routeName }}
  {{ else }}
  {{- if not (empty .Values.service.hostname) }}
  host: decisionserverconsole.odm.{{ .Release.Name }}.{{ .Values.service.hostname }}
  {{- end }}
  {{- end }}
  port:
  {{- if .Values.service.enableTLS }}
    targetPort: decisionserverconsole-https
  tls:
    termination: passthrough
  {{ else }}
    targetPort: decisionserverconsole
  {{- end }}
  to:
    kind: Service
    name:  {{ template "odm.decisionserverconsole.fullname" . }}
    weight: 100
  wildcardPolicy: None

{{- end }}
