{{- if and (.Values.oidc.enabled) (not (empty .Values.oidc.adminRef))  }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "odm.oidc-job-registration.fullname" . }}
  labels:
    run: {{ template "odm.oidc-registration.fullname" . }}
{{ include "odm-additional-labels" (dict "componentName" "oidc" "root" .) | indent 4 }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        run: {{ template "odm.oidc-job-registration.fullname" . }}
{{ include "odm-additional-labels" (dict "componentName" "oidc" "root" .) | indent 8 }}
{{ include "odm-annotations" . | indent 6 }}
    spec:
      securityContext:
        runAsNonRoot: true
        {{- if .Values.customization.runAsUser }}
        runAsUser: {{ .Values.customization.runAsUser }}
        fsGroup: 10000
        {{- end }}
{{ include "odm-seccomp-profile" . | indent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                {{- if and .Values.image.arch .Values.image.useArch }}
                - {{ .Values.image.arch }}
                {{- else }}
                - amd64
                - ppc64le
                - s390x
                {{- end }}
{{- if or (eq .Values.customization.vault "initcontainer") (and (.Values.vault.enabled) (eq .Values.vault.type "initcontainer")) }}
      initContainers:
{{- include "odm-init-container-template-full" (dict "initcontext" .Values.oidc.initContainer "root" . "containername" "odm.oidc-registration")  | indent 6 }}
{{- end }}
      containers:
      - name: {{ template "odm.oidc-registration.fullname" . }}
{{ include "image.tagOrDigest" (dict "containerName" "odm-decisionrunner" "containerTag" .Values.decisionRunner.tagOrDigest "root" .) | indent 8  }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
{{ include "odm-security-context" . | indent 8 }}
        command: ["/bin/bash", "-c", "/oidc/run.sh"]
        volumeMounts:
          - name: oidc
            mountPath: /oidc
          - name: redirect-uris
            mountPath: /redirect_uris
          - name: registration-url
            mountPath: /registration-url
          {{- if or (eq .Values.customization.vault "initcontainer") (and (.Values.vault.enabled) (eq .Values.vault.type "initcontainer")) }}
          - name: oidc-credentials
            mountPath: /oidc-credentials
          {{- else }}
          - name: oidc-client-id
            mountPath: /oidc-client-id
          - name: oidc-client-secret
            mountPath: /oidc-client-secret
          - name: oidc-username
            mountPath: /oidc-username
          - name: oidc-password
            mountPath: /oidc-password

  {{- if .Values.customization.readOnlyRootFilesystem }}
          - name: tmp-folder-emptydir
            mountPath: /tmp
            {{- end }}
          {{- end }}
      volumes:
        - name: oidc
          configMap:
            defaultMode: 0755
            name: {{ template "odm.oidc-registration-configmap.fullname" . }}
        - name: redirect-uris
          configMap:
          {{- if not (empty .Values.oidc.redirectUrisRef) }}
            name: {{ .Values.oidc.redirectUrisRef }}
          {{- else }}
            name: {{ template "odm.oidc-redirect-uris-configmap.fullname" . }}
          {{- end }}
            items:
              - key: redirect-uris
                path: redirect_uris.properties
        - name: registration-url
          configMap:
          {{- if not (empty .Values.oidc.redirectUrisRef) }}
            name: {{ .Values.oidc.redirectUrisRef }}
          {{- else }}
            name: {{ template "odm.oidc-redirect-uris-configmap.fullname" . }}
          {{- end }}
            items:
              - key: registration-url
                path: registration-url.properties
        {{- if or (eq .Values.customization.vault "initcontainer") (and (.Values.vault.enabled) (eq .Values.vault.type "initcontainer")) }}
{{- if and .Values.customization.ephemeralStorage (or (not (empty .Values.customization.ephemeralStorage.definition)) (not (empty .Values.customization.ephemeralStorage.className))) }}
{{ include "odm-ephemeral-volume-definition" . | indent 8 }}
{{ else }}
        - name: oidc-credentials
          emptyDir: {}
{{- end }}
{{- include "odm-ephemeral-volume-definition" . | indent 8 }}
        {{- else }}
        - name: oidc-client-id
          secret:
            {{- if not (empty .Values.oidc.clientRef) }}
            secretName: {{ .Values.oidc.clientRef }}
            {{- else }}
            secretName: {{ template "odm.oidc-client-id-secret.fullname" . }}
            {{- end }}
            items:
            - key: clientId
              path: oidc-client-id
        - name: oidc-client-secret
          secret:
            {{- if not (empty .Values.oidc.clientRef) }}
            secretName: {{ .Values.oidc.clientRef }}
            {{- else }}
            secretName: {{ template "odm.oidc-client-id-secret.fullname" . }}
            {{- end }}
            items:
            - key: clientSecret
              path: oidc-client-secret
        - name: oidc-username
          secret:
            secretName: {{ .Values.oidc.adminRef }}
            items:
            - key: adminUser
              path: oidc-username
        - name: oidc-password
          secret:
            secretName: {{ .Values.oidc.adminRef }}
            items:
            - key: adminPassword
              path: oidc-password
        {{- end }}
  {{- if .Values.customization.readOnlyRootFilesystem }}
{{- if and .Values.customization.ephemeralStorage (or (not (empty .Values.customization.ephemeralStorage.definition)) (not (empty .Values.customization.ephemeralStorage.className))) }}
{{ include "odm-ephemeral-volume-definition" . | indent 8 }}
{{ else }}
        - name: tmp-folder-emptydir
          emptyDir: {}
{{- end }}
  {{- end }}
{{- if or (eq .Values.customization.vault "initcontainer") (and (.Values.vault.enabled) (eq .Values.vault.type "initcontainer")) }}
{{ include "odm-init-container-volume" (dict "initcontext" .Values.oidc.initContainer "root" . "containername" "odm.oidc-registration") | indent 8 }}
{{- end }}
      restartPolicy: Never
{{- include "odm-pullsecret-spec" . | indent 6 }}
{{- end }}
