{{- if .Values.customization.watcher.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ .Release.Name }}-odm-watcher-rolebinding
 labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/component: {{ template "odm.watcher.name" . }}
subjects:
- kind: ServiceAccount
  {{- if .Values.serviceAccountName }}
  name: {{ .Values.serviceAccountName }}
  {{- else }}
  name: {{ template "fullname" . }}-service-account
  {{- end }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-odm-watcher-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
