{{- if .Values.customization.watcher.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "odm.watcher-script-configmap.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/component: {{ template "odm.watcher.name" . }}
data:
  watcher.sh: |-
{{ .Files.Get "watcher/watcher.sh" | indent 4 }}
{{- end }}
