---
# Source: ibm-odm-prod/templates/dc-logging-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  odm-sno-uat-odm-dc-logging-configmap
  labels:
    app: odm-sno-uat-ibm-odm-prod
    chart: "ibm-odm-prod-25.1.10"
    release: "odm-sno-uat"
    heritage: "Helm"
    app.kubernetes.io/instance: odm-sno-uat
    app.kubernetes.io/name: ibm-odm-prod
    app.kubernetes.io/version: "9.5.0.1-IF010"
    app.kubernetes.io/component: decisionCenter
    app.kubernetes.io/part-of: odm
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: ibm-odm-prod-25.1.10
data:
  dc-logging: |
    <server>
      <logging hideMessage="SRVE9967W" traceFileName="stdout" traceFormat="BASIC" traceSpecification="*=audit:org.apache.solr.*=warning:com.ibm.rules.bdsl.search.solr.*=warning" consoleLogLevel="INFO"/>
      <!-- Uncomment to get access logs
      <httpAccessLogging filepath="/logs/access.log" id="accessLogging"/>
      -->
    </server>
