---
# Source: ibm-odm-prod/templates/ds-runtime-jvm-options-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  odm-sno-uat-odm-ds-runtime-jvm-options-configmap
  labels:
    app: odm-sno-uat-ibm-odm-prod
    chart: "ibm-odm-prod-25.1.10"
    release: "odm-sno-uat"
    heritage: "Helm"
    app.kubernetes.io/instance: odm-sno-uat
    app.kubernetes.io/name: ibm-odm-prod
    app.kubernetes.io/version: "9.5.0.1-IF010"
    app.kubernetes.io/component: decisionServerRuntime
    app.kubernetes.io/part-of: odm
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: ibm-odm-prod-25.1.10
data:
  dsr-jvm-options: |
    -Duser.timezone=Europe/Paris
    -Dcom.ibm.jsse2.overrideDefaultTLS=true
    -Djdk.nativeDigest=false
    -Xtune:throughput
