apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Just point to the directory where your 20+ helm template files live
resources:
- ./ibm-odm-prod

# Inject the sync wave into your specific secret
patches:
  - target:
      kind: Secret
      name: odm-sno-uat-ds-auth-sso
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-wave
        value: "-1"
