---
# Source: ibm-odm-prod/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odm-sno-uat-ibm-odm-prod-service-account
  labels:
    app: odm-sno-uat-ibm-odm-prod
    chart: "ibm-odm-prod-25.1.10"
    release: "odm-sno-uat"
    heritage: "Helm"
    app.kubernetes.io/instance: odm-sno-uat
    app.kubernetes.io/name: ibm-odm-prod
    app.kubernetes.io/version: "9.5.0.1-IF010"
    app.kubernetes.io/component: odm
    app.kubernetes.io/part-of: odm
    app.kubernetes.io/managed-by: helm
    helm.sh/chart: ibm-odm-prod-25.1.10
automountServiceAccountToken: false
imagePullSecrets:
  - name: ibm-entitlement-key
