apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Helm chart configuration
helmCharts:
  - name: ibm-odm-prod
    repo: oci://cp.icr.io/cp/cp4a/odm
    version: 25.1.10
    releaseName: odm-sno-uat
    namespace: odm-uat
    valuesFile: ../../values/odm-sno-uat.yaml
    includeCRDs: true

# Resources to deploy (secrets must be created first)
resources:
  - odm-sno-uat-ds-auth-sso.yaml
  - odm-sno-uat-ds-cert.yaml

# Patches to apply after Helm rendering
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ".*-decisionserverruntime"

    patch: |-
      - op: add
        path: /spec/template/spec/terminationGracePeriodSeconds
        value: 90

      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe/httpGet

      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/exec
        value:
          command:
            - curl
            - -k
            - https://localhost:9443/DecisionService/
            - --cert
            - /opt/ibm/wlp/usr/servers/defaultServer/security/volume/tls.crt
            - --key
            - /opt/ibm/wlp/usr/servers/defaultServer/security/volume/tls.key

      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe/httpGet

      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/exec
        value:
          command:
            - cat
            - /opt/ibm/wlp/usr/servers/defaultServer/serverStartupCheck.complete

      - op: remove
        path: /spec/template/spec/containers/0/startupProbe/httpGet

      - op: add
        path: /spec/template/spec/containers/0/startupProbe/exec
        value:
          command:
            - curl
            - -k
            - https://localhost:9443/DecisionService/
            - --cert
            - /opt/ibm/wlp/usr/servers/defaultServer/security/volume/tls.crt
            - --key
            - /opt/ibm/wlp/usr/servers/defaultServer/security/volume/tls.key
