{{- if eq (include "isInternalDatabase" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "odm.dbserver.fullname" . }}
  labels:
    run: {{ template "odm.dbserver.fullname" . }}
{{ include "odm-additional-labels" (dict "componentName" "dbserver" "root" . "config" .Values.internalDatabase) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      run: {{ template "odm.dbserver.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        run: {{ template "odm.dbserver.fullname" . }}
{{ include "odm-additional-labels" (dict "componentName" "dbserver" "root" . "config" .Values.internalDatabase) | indent 8 }}
      annotations:
{{ include "odm-annotations" . | indent 8 }}
        productChargedContainers: ""
{{ include "odm-additional-annotations" (dict "root" . "config" .Values.internalDatabase) | indent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                {{- if and .Values.image.arch .Values.image.useArch }}
                - {{ .Values.image.arch }}
                {{- else }}
                - amd64
                - ppc64le
                - s390x
                {{- end }}
{{ include "odm-serviceAccountName" . | indent 6 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.internalDatabase.runAsUser }}
        fsGroup: {{ .Values.internalDatabase.runAsUser }}
{{ include "odm-seccomp-profile" . | indent 8 }}
      volumes:
      - name: postgres-secret
        {{- if .Values.internalDatabase.secretCredentials }}
        {{- include "secret-or-spc" (dict "root" . "ref" .Values.internalDatabase.secretCredentials) | indent 8 -}}
        {{- else }}
        secret:
          secretName: {{ template "odm.secret.fullname" . }}
        {{- end }}
      {{- if .Values.internalDatabase.persistence.enabled }}
      - name: {{ template "fullname" . }}-volume
        persistentVolumeClaim:
          claimName: {{ template "odm.persistenceclaim.fullname" . }}
      {{- else }}
        {{- if .Values.customization.readOnlyRootFilesystem }}
{{- if not (and .Values.customization.ephemeralStorage (or (not (empty .Values.customization.ephemeralStorage.definition)) (not (empty .Values.customization.ephemeralStorage.className)))) }}
      - name: {{ template "fullname" . }}-volume
        emptyDir: {}
{{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.customization.readOnlyRootFilesystem }}
      {{- if and .Values.customization.ephemeralStorage (or (not (empty .Values.customization.ephemeralStorage.definition)) (not (empty .Values.customization.ephemeralStorage.className))) }}
{{ include "odm-ephemeral-volume-definition" . | indent 6 }}
      {{- else }}
      - name: tmp-folder-volume
        emptyDir: {}
      - name: pgsql-run-folder-volume
        emptyDir: {}
      {{- end }}
      {{- end }}

      containers:
      - name: {{ template "odm.dbserver.fullname" . }}
{{ include "image.tagOrDigest" (dict "containerName" "dbserver" "containerTag" .Values.internalDatabase.tagOrDigest "root" .) | indent 8  }}
        securityContext:
          runAsUser: {{ .Values.internalDatabase.runAsUser }}
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem:  {{ .Values.customization.readOnlyRootFilesystem }}
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRESQL_DATABASE
          value: "{{ .Values.internalDatabase.databaseName }}"
        - name: POSTGRES_DB
          value: "{{ .Values.internalDatabase.databaseName }}"
        - name: POSTGRESQL_USER_FILE
          value: /var/run/postgresql/secrets/db-user
        - name: POSTGRESQL_PASSWORD_FILE
          value: /var/run/postgresql/secrets/db-password
        {{- if eq .Values.decisionCenter.persistenceLocale "en_US" }}
        - name: SAMPLE
          value: "{{ .Values.internalDatabase.populateSampleData }}"
        {{- if .Values.internalDatabase.populateSampleData }}
        {{- if not (empty .Values.decisionCenter.contextRoot) }}
        - name: ODM_CONTEXT_ROOT
          value: "{{ .Values.decisionCenter.contextRoot }}"
        {{- end }}
        {{- end }}
        {{- end }}
        ports:
        - name: db-port
          containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: db-port
          {{- if lt (int .Values.readinessProbe.initialDelaySeconds) 60 }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          {{- end }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        livenessProbe:
          tcpSocket:
            port: db-port
          {{- if lt (int .Values.livenessProbe.initialDelaySeconds) 60 }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          {{- end }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        startupProbe:
          tcpSocket:
            port: db-port
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
        volumeMounts:
          - name: postgres-secret
            mountPath: "/var/run/postgresql/secrets/"
            readOnly: true
        {{- if .Values.internalDatabase.persistence.enabled }}
          - name: {{ template "fullname" . }}-volume
            mountPath: /var/lib/pgsql/
            subPath : data
        {{- else }}
          {{- if .Values.customization.readOnlyRootFilesystem }}
          - {{- include "odm-ephemeral-volume-mount" (dict "root" . "volumeName" (printf "%s-volume" (include "fullname" .)) "subPath" "data") | nindent 12 }}
            mountPath: /var/lib/pgsql/
            {{- if not (and .Values.customization.ephemeralStorage (or (not (empty .Values.customization.ephemeralStorage.definition)) (not (empty .Values.customization.ephemeralStorage.className)))) }}
            subPath: data
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if .Values.customization.readOnlyRootFilesystem }}
          - {{- include "odm-ephemeral-volume-mount" (dict "root" . "volumeName" "tmp-folder-volume" "subPath" "tmp") | nindent 12 }}
            mountPath: /tmp
          - {{- include "odm-ephemeral-volume-mount" (dict "root" . "volumeName" "pgsql-run-folder-volume" "subPath" "pgsql-run") | nindent 12 }}
            mountPath: /var/run/postgresql
        {{- end }}
        resources:
{{ toYaml .Values.internalDatabase.resources | indent 10 }}
{{- include "odm-pullsecret-spec" . | indent 6 }}
{{- end }}
