{{- if and (empty .Values.decisionCenter.loggingRef) (.Values.decisionCenter.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "odm.dc-logging-configmap.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionCenter" "root" .) | indent 4 }}
data:
{{- if or .Values.customization.enableAuditLog .Values.decisionServerConsole.enableAuditLog }}
  dc-logging: |
    <server>
      <logging hideMessage="SRVE9967W" traceFileName="stdout" traceFormat="BASIC" traceSpecification="*=audit:org.apache.solr.*=warning:com.ibm.rules.bdsl.search.solr.*=warning" consoleLogLevel="INFO"/>
      <auditFileHandler logDirectory="/logs" maxFiles="5" maxFileSize="5" compact="true"/>
      <!-- Uncomment to get access logs
      <httpAccessLogging filepath="/logs/access.log" id="accessLogging"/>
      -->
    </server>
{{- else }}
  dc-logging: |
    <server>
      <logging hideMessage="SRVE9967W" traceFileName="stdout" traceFormat="BASIC" traceSpecification="*=audit:org.apache.solr.*=warning:com.ibm.rules.bdsl.search.solr.*=warning" consoleLogLevel="INFO"/>
      <!-- Uncomment to get access logs
      <httpAccessLogging filepath="/logs/access.log" id="accessLogging"/>
      -->
    </server>
{{- end }}
{{- end }}
