{{- if and (or ( not (empty .Values.decisionCenter.monitorRef)) ( not (empty .Values.customization.monitorRef))) (.Values.decisionCenter.enabled) (.Values.customization.enablePodMonitor) ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PodMonitor") }}
kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ template "odm-dc-pod-monitor.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionCenter" "root" .) | indent 4 }}
spec:
  selector:
    matchLabels:
      run: {{ template "odm.decisioncenter.fullname" . }}
  podMetricsEndpoints:
  - port: dc-port
{{- if .Values.service.enableTLS }}
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
{{- else }}
    scheme: http
{{- end }}
{{- end -}}
