{{- if and .Values.service.enableRoute .Values.decisionCenter.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{  template "odm-dc-route.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionCenter" "root" .) | indent 4 }}
spec:
  {{- if not (empty .Values.decisionCenter.routeName ) }}
  host: {{ .Values.decisionCenter.routeName }}
  {{ else }}
  {{- if not (empty .Values.service.hostname) }}
  host: decisioncenter.odm.{{ .Release.Name }}.{{ .Values.service.hostname }}
  {{- end  }}
  {{- end  }}
  port:
  {{- if .Values.service.enableTLS }}
    targetPort: decisioncenter-https
  tls:
    termination: passthrough
  {{ else }}
    targetPort: decisioncenter
  {{- end }}
  to:
    kind: Service
    name:  {{ template "odm.decisioncenter.fullname" . }}
    weight: 100
  wildcardPolicy: None

{{- end }}
