{{- if and (empty .Values.decisionRunner.jvmOptionsRef) (.Values.decisionRunner.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "odm.dr-jvm-options-configmap.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionRunner" "root" .) | indent 4 }}
data:
  dr-jvm-options: |
    -Duser.timezone=Europe/Paris
    -Dcom.ibm.jsse2.overrideDefaultTLS=true
    -Djdk.nativeDigest=false
    --enable-native-access=ALL-UNNAMED
    {{- if .Values.customization.enableFips }}
    -Dsemeru.fips=true
    -Dsemeru.customprofile=OpenJCEPlusFIPS.FIPS140-3-withPKCS11
    -Djava.security.properties=/opt/ibm/wlp/usr/servers/defaultServer/jvm/enablefips-java.security
    {{- end }}
{{- end }}
