{{- if and .Values.decisionServerRuntime.enabled .Values.service.enableRoute }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "odm-ds-runtime-route.fullname" . }}
  annotations:
    haproxy.router.openshift.io/balance: leastconn
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionServerRuntime" "root" .) | indent 4 }}
spec:
  {{- if not (empty .Values.decisionServerRuntime.routeName ) }}
  host: {{ .Values.decisionServerRuntime.routeName }}
  {{ else }}
  {{- if not (empty .Values.service.hostname) }}
  host: decisionserverruntime.odm.{{ .Release.Name }}.{{ .Values.service.hostname }}
  {{- end }}
  {{- end }}
  port:
  {{- if .Values.service.enableTLS }}
    targetPort: decisionserverruntime-https
  tls:
    termination: passthrough
  {{ else }}
    targetPort: decisionserverruntime
  {{- end }}
  to:
    kind: Service
    name:  {{ template "odm.decisionserverruntime.fullname" . }}
    weight: 100
  wildcardPolicy: None

{{- end }}
