{{- if .Values.decisionServerRuntime.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "odm.decisionserverruntime.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionServerRuntime" "root" .) | indent 4 }}
spec:
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    run: {{ template "odm.decisionserverruntime.fullname" . }}
{{ include "odm-service-type" . | indent 2 }}
{{- include "odm-service-ipfamilypolicy" . | indent 2 }}
{{- include "odm-service-ip-families" . | indent 2 }}
  ports:
   - protocol: TCP
     port: 9443
     {{- if .Values.service.enableTLS }}
     name: decisionserverruntime-https
     targetPort: 9443
     {{- if .Values.dba.istio.enabled }}
     name: decisionserverruntime
     targetPort: 9080
     {{- end }}
     {{ else }}
     name: decisionserverruntime
     targetPort: 9080
     {{- end }}
{{- end }}
