{{- if not (empty (.Values.decisionServerRuntime.podDisruptionBudget)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "odm-dsr-pdb.fullname" . }}
spec:
{{ toYaml .Values.decisionServerRuntime.podDisruptionBudget | indent 2 }}
  selector:
    matchLabels:
      run: {{ template "odm.decisionserverruntime.fullname" . }}
{{- end }}
