{{- if and (.Values.externalDatabase.decisionCenter.serverName) (empty  .Values.externalDatabase.decisionCenter.secretCredentials) (empty .Values.externalDatabase.decisionServer.secretCredentials) (empty .Values.externalDatabase.secretCredentials) (empty .Values.internalDatabase.secretCredentials) (empty .Values.customization.vault) (not .Values.vault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "odm.secret-dc.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "odm" "root" .) | indent 4 }}
type: Opaque
data:
  db-user: {{ (include "odm-external-sec-dc-user" .)  | b64enc | quote }}
  db-password:  {{ (include "odm-external-sec-dc-password" .)  | b64enc | quote }}
{{- end }}
