apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-odm-sno-uat
  namespace: openshift-gitops
spec:
  project: default
  sources:
    # Source 1: The Helm Chart (Treated as a helm repo type implicitly by Argo CD)
    - repoURL: 'https://github.com/cipherdmg/gitopts-getting-started'
      targetRevision: HEAD
      # Point path to the directory containing the tgz file
      path: helm/helm/ibm-odm-prod
      helm:
        # Define the exact name of the chart package inside that folder
        chart: ibm-odm-prod
        valueFiles:
          # Reference the values file via the second source ($values-repo)
          - $values-repo/helm/values/odm-sno-uat.yaml

    # Source 2: The Git repository context for your values file
    - repoURL: 'https://github.com/cipherdmg/gitopts-getting-started'
      targetRevision: HEAD
      ref: values-repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ibm-odm-uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
~