apiVersion: v2
appVersion: 9.5.0.1-IF010
description: 'IBM Operational Decision Manager  License By installing this product
  you accept the following license terms: https://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-XVKV-NLU3EQ'
home: https://www.ibm.com/docs/en/odm/9.5.0?topic=production-installing-helm-release-odm
icon: https://raw.githubusercontent.com/ODMDev/ruledesigner/master/icons/automation-decision.png
keywords:
- OperationalDecisionManager
- businessrules
- Commercial
- s390x
- ppc64le
- amd64
- ICP
- RHOCP
- Middleware
kubeVersion: '>= 1.28.0-0'
maintainers:
- name: IBM
name: ibm-odm-prod
sources:
- https://github.com/IBM/charts/tree/master/stable
version: 25.1.10
