#
# oc -n "${REDHAT_GITOPTS_NAMESPACE}" get applications
# oc -n "${REDHAT_GITOPTS_NAMESPACE}" delete application odm
# delete_project --odm
#
#
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odm
  namespace: openshift-gitops
spec:
  destination:
    namespace: odm-sno-uat
    server: https://kubernetes.default.svc
  source:
    path: odm                        # <-- CHANGE THIS BACK TO YOUR FOLDER
    repoURL: https://github.com/cipherdmg/gitopts-getting-started
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m